-- 007_create_position_history.sql
-- Position History: daily snapshots for portfolio performance tracking.
-- One row per position per day. Powers performance charts and
-- time-weighted return calculations.
-- Generated by an end-of-day job after market close.

CREATE TABLE IF NOT EXISTS position_history (
  id                SERIAL PRIMARY KEY,
  account_id        INTEGER NOT NULL REFERENCES accounts(id) ON DELETE CASCADE,
  symbol            TEXT NOT NULL,
  date              DATE NOT NULL,
  quantity          NUMERIC(16, 6) NOT NULL,
  market_price      NUMERIC(16, 6) NOT NULL,
  market_value      NUMERIC(16, 2) NOT NULL,
  cost_basis        NUMERIC(16, 2) NOT NULL,
  unrealized_pnl    NUMERIC(16, 2) NOT NULL,
  created_at        TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (account_id, symbol, date)
);

CREATE INDEX idx_position_history_account_date ON position_history(account_id, date);
CREATE INDEX idx_position_history_symbol ON position_history(account_id, symbol, date);
