"use client"

import { use } from "react"
import Link from "next/link"
import { Sparkles } from "lucide-react"
import { Button } from "@/components/ui/button"
import { MarkdownMessage } from "@/components/ai/markdown-message"
import type { PortfolioReview } from "@/services/ai/portfolio-review-service"

interface PortfolioAnalyzeProps {
  reviewPromise: Promise<PortfolioReview>
}

export function PortfolioAnalyze({ reviewPromise }: PortfolioAnalyzeProps) {
  const review = use(reviewPromise)

  if (review.budgetExceeded) {
    return <UpgradeGate />
  }

  return (
    <div className="mx-auto flex w-full max-w-[880px] flex-col gap-4">
      {review.full ? (
        <MarkdownMessage content={review.full} className="text-base" />
      ) : (
        <p className="text-base leading-relaxed text-foreground">
          No analysis available yet. Add some holdings to your portfolio.
        </p>
      )}
      {review.model && review.model !== "n/a" && (
        <p className="text-xs text-muted-foreground">
          Generated by {review.model} · {new Date(review.createdAt).toLocaleString()}
        </p>
      )}
    </div>
  )
}

function UpgradeGate() {
  return (
    <div className="relative mx-auto w-full max-w-[880px]">
      <div
        aria-hidden="true"
        className="pointer-events-none flex select-none flex-col gap-4 blur-md"
      >
        <h2 className="text-xl font-semibold text-foreground">Portfolio Overview</h2>
        <p className="text-base leading-relaxed text-foreground">
          Your portfolio shows balanced exposure across major sectors with a notable
          tilt toward technology. Cloud-infrastructure names anchor the equity sleeve
          while defensive holdings provide ballast against drawdowns.
        </p>
        <h3 className="text-lg font-semibold text-foreground">Risk Analysis</h3>
        <p className="text-base leading-relaxed text-foreground">
          The current portfolio beta sits modestly above the broader market, implying
          higher upside capture but also amplified volatility during corrections.
          Concentration in a few large holdings warrants periodic rebalancing.
        </p>
        <h3 className="text-lg font-semibold text-foreground">Recommendations</h3>
        <ul className="list-disc space-y-1 pl-5 text-base leading-relaxed text-foreground">
          <li>Trim outsized tech exposure into staples or healthcare.</li>
          <li>Consider adding a treasury or short-duration bond sleeve.</li>
          <li>Set price alerts on your top three positions.</li>
        </ul>
      </div>

      <div className="absolute inset-0 flex items-center justify-center p-4">
        <div className="flex max-w-md flex-col items-center gap-4 rounded-xl border border-border bg-card p-8 text-center shadow-lg">
          <div className="flex size-12 items-center justify-center rounded-lg bg-primary/10">
            <Sparkles className="size-6 text-primary" />
          </div>
          <div className="flex flex-col gap-2">
            <h3 className="text-lg font-semibold text-foreground">
              Upgrade to unlock AI portfolio reviews
            </h3>
            <p className="text-sm text-muted-foreground">
              StockMind Pro analyzes your holdings, surfaces concentration risk, and
              suggests rebalancing moves tailored to your portfolio.
            </p>
          </div>
          <Button asChild className="w-full">
            <Link href="/settings/payments">Upgrade to Pro</Link>
          </Button>
        </div>
      </div>
    </div>
  )
}

export function PortfolioAnalyzeSkeleton() {
  return (
    <div className="mx-auto flex w-full max-w-[880px] animate-pulse flex-col gap-4">
      <div className="space-y-3">
        <div className="h-6 w-40 rounded bg-secondary" />
        <div className="space-y-2">
          <div className="h-4 w-full rounded bg-secondary" />
          <div className="h-4 w-11/12 rounded bg-secondary" />
        </div>
        <div className="h-6 w-56 rounded bg-secondary" />
        <div className="space-y-2 pl-5">
          <div className="h-4 w-10/12 rounded bg-secondary" />
          <div className="h-4 w-9/12 rounded bg-secondary" />
          <div className="h-4 w-11/12 rounded bg-secondary" />
          <div className="h-4 w-8/12 rounded bg-secondary" />
        </div>
      </div>
      <p className="text-xs text-muted-foreground">Generating analysis…</p>
    </div>
  )
}
