"use client"

import { use } from "react"
import { MarkdownMessage } from "@/components/ai/markdown-message"
import type { PortfolioReview } from "@/services/ai/portfolio-review-service"

interface PortfolioAnalyzeProps {
  reviewPromise: Promise<PortfolioReview>
}

export function PortfolioAnalyze({ reviewPromise }: PortfolioAnalyzeProps) {
  const review = use(reviewPromise)

  return (
    <div className="mx-auto flex w-full max-w-[880px] flex-col gap-4">
      {review.full ? (
        <MarkdownMessage content={review.full} className="text-base" />
      ) : (
        <p className="text-base leading-relaxed text-foreground">
          No analysis available yet. Add some holdings to your portfolio.
        </p>
      )}
      {review.model && review.model !== "n/a" && (
        <p className="text-xs text-muted-foreground">
          Generated by {review.model} · {new Date(review.createdAt).toLocaleString()}
        </p>
      )}
    </div>
  )
}

export function PortfolioAnalyzeSkeleton() {
  return (
    <div className="mx-auto flex w-full max-w-[880px] animate-pulse flex-col gap-4">
      <div className="space-y-3">
        <div className="h-6 w-40 rounded bg-secondary" />
        <div className="space-y-2">
          <div className="h-4 w-full rounded bg-secondary" />
          <div className="h-4 w-11/12 rounded bg-secondary" />
        </div>
        <div className="h-6 w-56 rounded bg-secondary" />
        <div className="space-y-2 pl-5">
          <div className="h-4 w-10/12 rounded bg-secondary" />
          <div className="h-4 w-9/12 rounded bg-secondary" />
          <div className="h-4 w-11/12 rounded bg-secondary" />
          <div className="h-4 w-8/12 rounded bg-secondary" />
        </div>
      </div>
      <p className="text-xs text-muted-foreground">Generating analysis…</p>
    </div>
  )
}
