"use client"

import { use } from "react"
import { Sparkles } from "lucide-react"
import type { PortfolioReview } from "@/services/ai/portfolio-review-service"

interface PortfolioAnalyzeProps {
  reviewPromise: Promise<PortfolioReview>
}

export function PortfolioAnalyze({ reviewPromise }: PortfolioAnalyzeProps) {
  const review = use(reviewPromise)

  return (
    <div className="flex flex-col gap-4 rounded-xl border border-border bg-card p-6">
      <div className="flex items-center gap-2">
        <Sparkles className="size-5 text-primary" />
        <h3 className="text-lg font-semibold text-primary">
          AI Portfolio Analysis
        </h3>
      </div>
      <p className="whitespace-pre-wrap text-sm leading-relaxed text-foreground">
        {review.full || "No analysis available yet. Add some holdings to your portfolio."}
      </p>
      {review.model && review.model !== "n/a" && (
        <p className="text-xs text-muted-foreground">
          Generated by {review.model} · {new Date(review.createdAt).toLocaleString()}
        </p>
      )}
    </div>
  )
}

export function PortfolioAnalyzeSkeleton() {
  return (
    <div className="flex animate-pulse flex-col gap-4 rounded-xl border border-border bg-card p-6">
      <div className="flex items-center gap-2">
        <Sparkles className="size-5 text-primary/40" />
        <div className="h-5 w-48 rounded bg-secondary" />
      </div>
      <div className="space-y-2">
        <div className="h-3 w-full rounded bg-secondary" />
        <div className="h-3 w-11/12 rounded bg-secondary" />
        <div className="h-3 w-10/12 rounded bg-secondary" />
        <div className="h-3 w-full rounded bg-secondary" />
        <div className="h-3 w-9/12 rounded bg-secondary" />
      </div>
      <p className="text-xs text-muted-foreground">Generating analysis…</p>
    </div>
  )
}
